-- MySQL Script generated by MySQL Workbench
-- fr. 28. aug. 2020 kl. 10.18 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`borettslag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`borettslag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NULL DEFAULT NULL,
  `adresse` VARCHAR(255) NULL DEFAULT NULL,
  `antall_blokker` INT NULL DEFAULT NULL,
  `etableringsar` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blokk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`blokk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresse` INT NULL DEFAULT NULL,
  `antall_leiligheter` INT NULL DEFAULT NULL,
  `etasjer` INT NULL DEFAULT NULL,
  `borettslag` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_borettslag_idx` (`borettslag` ASC) VISIBLE,
  CONSTRAINT `fk_borettslag`
    FOREIGN KEY (`borettslag`)
    REFERENCES `mydb`.`borettslag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`andelseier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`andelseier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornavn` VARCHAR(45) NULL DEFAULT NULL,
  `etternavn` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `borettslag` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_borettslag_idx` (`borettslag` ASC) VISIBLE,
  CONSTRAINT `fk_borettslag`
    FOREIGN KEY (`borettslag`)
    REFERENCES `mydb`.`borettslag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leilighet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leilighet` (
  `leilighet_nr` INT NOT NULL,
  `etasje` INT NULL DEFAULT NULL,
  `areal` INT NULL DEFAULT NULL,
  `antall_rom` INT NULL DEFAULT NULL,
  `blokk` INT NULL DEFAULT NULL,
  `eier` INT NULL DEFAULT NULL,
  PRIMARY KEY (`leilighet_nr`),
  INDEX `blokk_fk_idx` (`blokk` ASC) VISIBLE,
  INDEX `fk_eier_idx` (`eier` ASC) VISIBLE,
  CONSTRAINT `blokk_fk`
    FOREIGN KEY (`blokk`)
    REFERENCES `mydb`.`blokk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eier`
    FOREIGN KEY (`eier`)
    REFERENCES `mydb`.`andelseier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
